"""empty message

Revision ID: 20a0d675823e
Revises: 418c6fb00be7
Create Date: 2021-03-20 17:19:19.081841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a0d675823e'
down_revision = '418c6fb00be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('room_name', sa.VARCHAR(length=20), nullable=True, comment='聊天室名字'))
    op.create_unique_constraint(None, 'chat_room', ['room_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_room', type_='unique')
    op.drop_column('chat_room', 'room_name')
    # ### end Alembic commands ###
