"""empty message

Revision ID: 30d4137bfd58
Revises: 5e5f0b4026bb
Create Date: 2021-03-20 17:30:09.772587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d4137bfd58'
down_revision = '5e5f0b4026bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_room', 'update_at')
    # ### end Alembic commands ###
