"""empty message

Revision ID: 5e5f0b4026bb
Revises: c2dbecd81b88
Create Date: 2021-03-20 17:29:44.342965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5f0b4026bb'
down_revision = 'c2dbecd81b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_room', 'create_at')
    # ### end Alembic commands ###
