"""empty message

Revision ID: a2cd49eb5857
Revises: 20a0d675823e
Create Date: 2021-03-20 17:19:43.499352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cd49eb5857'
down_revision = '20a0d675823e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('user_id', sa.BigInteger(), nullable=False, comment='房间主人id'))
    op.create_unique_constraint(None, 'chat_room', ['user_id'])
    op.create_foreign_key(None, 'chat_room', 'users', ['user_id'], ['union_id'], ondelete='CASCSDE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_room', type_='foreignkey')
    op.drop_constraint(None, 'chat_room', type_='unique')
    op.drop_column('chat_room', 'user_id')
    # ### end Alembic commands ###
