"""empty message

Revision ID: a570f50924a5
Revises: 29fb0ec3b24f
Create Date: 2021-03-20 17:27:42.481951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a570f50924a5'
down_revision = '29fb0ec3b24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_room', 'update_at')
    op.drop_column('chat_room', 'room_status')
    op.drop_column('chat_room', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('create_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('chat_room', sa.Column('room_status', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='房间状态,0 未开始，1已开始'))
    op.add_column('chat_room', sa.Column('update_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
