"""empty message

Revision ID: a749a1313cc6
Revises: c0fb15cb17a9
Create Date: 2021-03-20 17:11:54.672201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a749a1313cc6'
down_revision = 'c0fb15cb17a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('union_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='聊天室id'),
    sa.Column('room_name', sa.VARCHAR(length=20), nullable=False, comment='聊天室名字'),
    sa.Column('describe', sa.VARCHAR(length=500), nullable=True, comment='房间简介'),
    sa.Column('sid', sa.VARCHAR(length=100), nullable=True, comment='房间sid'),
    sa.Column('number', sa.VARCHAR(length=7), nullable=False, comment='房间编号, 1356879'),
    sa.Column('room_status', sa.SmallInteger(), nullable=True, comment='房间状态,0 未开始，1已开始'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('union_id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('room_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
