"""empty message

Revision ID: c0fb15cb17a9
Revises: 667ce392b47c
Create Date: 2021-03-20 17:06:08.433253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0fb15cb17a9'
down_revision = '667ce392b47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='room')
    op.drop_constraint('room_ibfk_1', 'room', type_='foreignkey')
    op.drop_column('room', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='房间主人id'))
    op.create_foreign_key('room_ibfk_1', 'room', 'users', ['user_id'], ['union_id'])
    op.create_index('user_id', 'room', ['user_id'], unique=True)
    # ### end Alembic commands ###
