"""empty message

Revision ID: c9e46ff8770e
Revises: e8a156b7edd9
Create Date: 2021-03-20 17:24:28.986034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e46ff8770e'
down_revision = 'e8a156b7edd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('number', sa.VARCHAR(length=7), nullable=True, comment='房间编号, 1356879'))
    op.add_column('chat_room', sa.Column('room_status', sa.SmallInteger(), nullable=True, comment='房间状态,0 未开始，1已开始'))
    op.create_unique_constraint(None, 'chat_room', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_room', type_='unique')
    op.drop_column('chat_room', 'room_status')
    op.drop_column('chat_room', 'number')
    # ### end Alembic commands ###
