"""empty message

Revision ID: cc003b318e7e
Revises: a2cd49eb5857
Create Date: 2021-03-20 17:23:23.396603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc003b318e7e'
down_revision = 'a2cd49eb5857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('union_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='聊天室id'),
    sa.Column('room_name', sa.VARCHAR(length=20), nullable=True, comment='聊天室名字'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='房间主人id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.union_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('union_id'),
    sa.UniqueConstraint('room_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_room')
    # ### end Alembic commands ###
