"""empty message

Revision ID: e61ef99641f6
Revises: 786fb01614ad
Create Date: 2021-03-20 16:45:00.330521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61ef99641f6'
down_revision = '786fb01614ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('union_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='聊天室id'),
    sa.Column('room_name', sa.VARCHAR(length=20), nullable=False, comment='聊天室名字'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='房间主人id'),
    sa.Column('describe', sa.VARCHAR(length=500), nullable=True, comment='房间简介'),
    sa.Column('sid', sa.VARCHAR(length=100), nullable=True, comment='房间sid'),
    sa.Column('number', sa.VARCHAR(length=7), nullable=False, comment='房间编号, 1356879'),
    sa.Column('room_status', sa.SmallInteger(), nullable=True, comment='房间状态,0 未开始，1已开始'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.union_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('union_id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('room_name'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
