"""empty message

Revision ID: e8a156b7edd9
Revises: cc003b318e7e
Create Date: 2021-03-20 17:24:00.149694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a156b7edd9'
down_revision = 'cc003b318e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('describe', sa.VARCHAR(length=500), nullable=True, comment='房间简介'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_room', 'describe')
    # ### end Alembic commands ###
